- name: Assignment2 NETWORK AUTOMATION
  
 - hosts: webservers

  become: yes

  tasks:
 
  - name: Installing nginx web server 

    apt:

      name: nginx

      state: present

      update_cache: true
    notify:
    - start nginx

 

  - name: Installing php7.4-fpm 

    apt:

      name: php7.4-fpm

      state: present

      update_cache: true

    notify:

    - start php7.4-fpm
      - name: Setting up nginx.conf 
    template:
       src: "./nginx.conf"
       dest: "/etc/nginx/nginx.conf"
    notify:
    - restart php7.4-fpm
    - restart nginx



  - name: Delete default
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent
    notify: 
    - restart nginx

  - name: Setting up Nginx
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: Linking default 
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link
    notify: 
    - restart nginx
   

  - name: Setting Up index.php
    template:
      src: "./index.php"
      dest: "/var/www/html/index.php"
    notify:
    - restart nginx
    - start nginx
    - restart php7.4-fpm
    - start php7.4-fpm 
     handlers:

  - name: start php7.4-fpm
    service:

      name: php7.4-fpm

      state: started



  - name: start nginx
    service:

      name: nginx

      state: started


  - name: restart php7.4-fpm
    service:

      name: php7.4-fpm

      state: restarted
  - name: restart nginx

    service:

      name: nginx

      state: restarted
  
 
             
  

     
- hosts: all
  gather_facts: y
  
- hosts: haproxy
  become: true
 

  vars:
    haproxy_maxconns: 4096
    haproxy_backlog: 2
    haproxy_timeout_q: 400ms
    haproxy_timoutconnect: 5000ms
    haproxy_timeoutclient: 5000ms
    haproxy_timoutserver: 5000ms
    haproxy_http_timeout: 15s
    haproxy_balance: leastconn
    haproxy_frontend_port: 80

  tasks:
  
  - name: Update apt cache
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200

  - name: Installing haproxy package
    become: true
    apt:
      name: haproxy
      state: latest   

  - name: upgrade packages
    apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes
    notify:
      - run haproxy      

  - name: collect information from servers
    setup:
      filter: ansible_default_ipv4.address   


  - name: Removing existing default_haproxy_cfg
    file:
       path: "/etc/haproxy/haproxy.cfg"
       state: absent
    notify:
    - restart haproxy 

  - name: Deploy HAProxy configuration
    template:
      src: ./haproxy.cfg.j2
      dest: "/etc/haproxy/haproxy.cfg"
    notify:
      - restart haproxy
      - run haproxy

  handlers:

  - name: run haproxy
    service:
      name: haproxy
      state: started

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
      
- hosts: webservers
  gather_facts: y
  
  tasks:
  
  - name: restart nginx
    service:
       name: nginx
       state: restarted
    become: yes

